// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629182136_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.HasIndex("PlaceId", "ParentCommentId")
                        .HasDatabaseName("IX_Comments_PlaceId_ParentCommentId");

                    b.HasIndex("PostId", "ParentCommentId")
                        .HasDatabaseName("IX_Comments_PostId_ParentCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Backend.Models.CommentVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId", "CommentId")
                        .IsUnique();

                    b.ToTable("CommentVotes");
                });

            modelBuilder.Entity("Backend.Models.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Communities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6354),
                            Description = "Play football with friends or join a local team. A great team sport that builds endurance, coordination, and teamwork skills.",
                            Name = "Football",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6362)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6750),
                            Description = "Shoot hoops at your local court. Can be played solo for practice or in teams for competitive games.",
                            Name = "Basketball",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6750)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6751),
                            Description = "Play beach or indoor volleyball. A fun team sport that doesn't require extensive equipment.",
                            Name = "Volleyball",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6752)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6752),
                            Description = "America's pastime - bat, pitch, and field in this strategic team sport.",
                            Name = "Baseball",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6753)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6754),
                            Description = "A high-intensity contact sport requiring strength, speed, and teamwork.",
                            Name = "Rugby",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6754)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6759),
                            Description = "Fast-paced indoor sport combining elements of basketball and soccer.",
                            Name = "Handball",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6759)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6760),
                            Description = "Throw, dodge, and catch in this exciting and energetic team game.",
                            Name = "Dodgeball",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6760)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6761),
                            Description = "Tackle football with strategic plays and intense physicality.",
                            Name = "American Football",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6761)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6762),
                            Description = "A classic racket sport that can be played in singles or doubles. Great for improving reflexes and cardiovascular fitness.",
                            Name = "Tennis",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6762)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6764),
                            Description = "A fast-paced racket sport that can be played casually or competitively. Great for reflexes and agility.",
                            Name = "Badminton",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6764)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6765),
                            Description = "Fast-paced indoor sport requiring quick reflexes. Can be played competitively or just for fun.",
                            Name = "Table Tennis (Ping Pong)",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6765)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6766),
                            Description = "A paddle sport combining elements of tennis, badminton, and table tennis. Easy to learn and very social.",
                            Name = "Padel",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6766)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6767),
                            Description = "Take a simple walk around your neighborhood or local park. Perfect for clearing your mind and getting light exercise.",
                            Name = "Walking",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6767)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6768),
                            Description = "Explore nature trails and mountain paths. From easy trails to challenging climbs, there's a hike for everyone.",
                            Name = "Hiking",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6768)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6769),
                            Description = "Whether you're training for a marathon or just want to stay fit, running is an accessible and effective exercise.",
                            Name = "Running/Jogging",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6769)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6770),
                            Description = "Ride a bicycle for leisure or exercise. Great for exploring your city or countryside while getting a good workout.",
                            Name = "Cycling",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6770)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6771),
                            Description = "Observe and identify birds in their natural habitat. A peaceful outdoor community that connects you with nature.",
                            Name = "Bird Watching",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6771)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6772),
                            Description = "Enjoy outdoor meals in parks or scenic locations. Great for relaxation and socializing.",
                            Name = "Picnicking",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6773)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6773),
                            Description = "Observe the night sky, constellations, and celestial events. A peaceful and awe-inspiring community.",
                            Name = "Stargazing",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6774)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6790),
                            Description = "Throw a frisbee in the park. Can be casual tossing or competitive ultimate frisbee.",
                            Name = "Frisbee",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6790)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6791),
                            Description = "Practice yoga for flexibility, strength, and mental clarity. Suitable for all levels and can be done at home or in a studio.",
                            Name = "Yoga",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6791)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6792),
                            Description = "Build strength and muscle through resistance training. Can be done at the gym or at home with appropriate equipment.",
                            Name = "Weight Training",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6792)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6793),
                            Description = "High-energy stationary bike workout often done in group classes.",
                            Name = "Spinning/Indoor Cycling",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6793)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6794),
                            Description = "Cardiovascular exercise routine performed to music, often in a group setting.",
                            Name = "Aerobics",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6794)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6808),
                            Description = "Improve flexibility and reduce muscle tension through dedicated stretching routines.",
                            Name = "Stretching",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6808)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6809),
                            Description = "Bodyweight exercises like push-ups, pull-ups, and squats. No equipment needed.",
                            Name = "Calisthenics",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6809)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6810),
                            Description = "Swim for fitness, recreation, or competition. Excellent full-body workout that's easy on the joints.",
                            Name = "Swimming",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6810)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6811),
                            Description = "Ride ocean waves on a surfboard. An exciting water sport that builds strength and balance.",
                            Name = "Surfing",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6811)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6812),
                            Description = "Paddle through calm waters or tackle rapids in a kayak. Great for exploring waterways and building upper body strength.",
                            Name = "Kayaking",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6812)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6813),
                            Description = "Stand-up paddleboarding on calm waters. Great core workout and peaceful way to explore.",
                            Name = "Paddleboarding (SUP)",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6813)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6814),
                            Description = "Intense team water sport combining swimming, ball handling, and strategy.",
                            Name = "Water Polo",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6814)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6815),
                            Description = "Explore underwater worlds with scuba equipment. Requires certification but offers unique experiences.",
                            Name = "Scuba Diving",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6815)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6816),
                            Description = "Swim on the water surface while viewing underwater attractions through a snorkel mask.",
                            Name = "Snorkeling",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6816)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6817),
                            Description = "Paddle a canoe through rivers, lakes, or calm seas. Great for nature exploration.",
                            Name = "Canoeing",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6817)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6818),
                            Description = "High-speed water sport on a personal watercraft. Thrilling and adrenaline-pumping.",
                            Name = "Jet Skiing",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6819)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6819),
                            Description = "Navigate waters using wind power in a sailboat. Combines skill, strategy, and nature.",
                            Name = "Sailing",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6820)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6820),
                            Description = "Express yourself through painting with watercolors, acrylics, or oils. Perfect for relaxation and creativity.",
                            Name = "Painting",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6821)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6821),
                            Description = "Sketch and draw with pencils, charcoal, or digital tools. A portable and accessible creative outlet.",
                            Name = "Drawing",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6822)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6822),
                            Description = "Capture moments and express your artistic vision through photography. Can be done with a phone or professional camera.",
                            Name = "Photography",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6823)
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6823),
                            Description = "Play the classic strategy game of chess. Improve your tactical thinking and problem-solving skills.",
                            Name = "Chess",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6824)
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6824),
                            Description = "Gather friends and family for board game nights. From strategy games to party games, there's something for everyone.",
                            Name = "Board Games",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6825)
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6825),
                            Description = "Play video games on console, PC, or mobile. From casual puzzle games to competitive esports.",
                            Name = "Video Gaming",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6826)
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6826),
                            Description = "Play poker, bridge, magic the gathering, or casual card games with friends.",
                            Name = "Card Games",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6827)
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6827),
                            Description = "Work on jigsaw puzzles, crosswords, sudoku, or other brain teasers.",
                            Name = "Puzzle Solving",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6828)
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6828),
                            Description = "Throw darts at a target board. Fun pub game that improves focus and precision.",
                            Name = "Darts",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6829)
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6829),
                            Description = "Play pool, snooker, or other cue sports at a table. Strategic and social community.",
                            Name = "Pool/Billiards",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6830)
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6830),
                            Description = "Test your knowledge in trivia nights or quiz games. Great for groups and learning.",
                            Name = "Trivia/Quiz Games",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6831)
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6831),
                            Description = "Solve puzzles and riddles to 'escape' from a themed room within a time limit.",
                            Name = "Escape Rooms",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6832)
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6832),
                            Description = "Give back to your community through volunteer work. A rewarding way to make a positive impact.",
                            Name = "Volunteering",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6833)
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6833),
                            Description = "Dive into books, whether fiction, non-fiction, or poetry. Expand your knowledge and imagination.",
                            Name = "Reading",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6834)
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6834),
                            Description = "Study celestial objects and phenomena. Combine observation with scientific learning.",
                            Name = "Astronomy",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6835)
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6835),
                            Description = "Practice mindfulness and meditation to reduce stress and improve mental clarity. Can be done anywhere.",
                            Name = "Meditation",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6836)
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6836),
                            Description = "Enjoy music for relaxation, motivation, or pure pleasure. Create playlists or explore new genres.",
                            Name = "Listening to Music",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6837)
                        },
                        new
                        {
                            Id = 113,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6837),
                            Description = "Downhill or cross-country skiing in winter. An exhilarating sport for snow enthusiasts.",
                            Name = "Skiing",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6838)
                        },
                        new
                        {
                            Id = 114,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6838),
                            Description = "Ride down snowy slopes on a snowboard. Dynamic and exciting winter sport.",
                            Name = "Snowboarding",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6839)
                        },
                        new
                        {
                            Id = 115,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6839),
                            Description = "Glide on ice at a rink. Fun winter community that builds balance and leg strength.",
                            Name = "Ice Skating",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6840)
                        },
                        new
                        {
                            Id = 116,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6840),
                            Description = "Fast-paced team sport played on ice. Requires skating ability and competitive spirit.",
                            Name = "Ice Hockey",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6841)
                        },
                        new
                        {
                            Id = 130,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6842),
                            Description = "Indoor or outdoor climbing that builds strength, problem-solving skills, and confidence.",
                            Name = "Rock Climbing",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6842)
                        },
                        new
                        {
                            Id = 132,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6842),
                            Description = "Ride and perform tricks on a skateboard. A creative sport that builds balance and coordination.",
                            Name = "Skateboarding",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6843)
                        },
                        new
                        {
                            Id = 133,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6843),
                            Description = "Navigate urban environments efficiently using running, jumping, and climbing. Develops athleticism and creativity.",
                            Name = "Parkour",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6844)
                        },
                        new
                        {
                            Id = 134,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6845),
                            Description = "Perform tricks and stunts on BMX bicycles. Combines cycling with extreme sports.",
                            Name = "BMX Biking",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6845)
                        },
                        new
                        {
                            Id = 135,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6846),
                            Description = "Ride bicycles off-road on rugged terrain. Adventurous and challenging.",
                            Name = "Mountain Biking",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6846)
                        },
                        new
                        {
                            Id = 138,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6847),
                            Description = "Spend nights outdoors in a tent or RV. Experience nature and disconnect from daily routines.",
                            Name = "Camping",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6847)
                        },
                        new
                        {
                            Id = 139,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6848),
                            Description = "Cast a line in rivers, lakes, or the ocean. A relaxing pastime that can be social or solitary.",
                            Name = "Fishing",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6848)
                        },
                        new
                        {
                            Id = 141,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6849),
                            Description = "Ride horses on trails or in arenas. Connect with animals while enjoying outdoor exercise.",
                            Name = "Horseback Riding",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6849)
                        },
                        new
                        {
                            Id = 143,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6850),
                            Description = "Play golf at a course or practice at a driving range. A social sport that combines skill and strategy.",
                            Name = "Golf",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6850)
                        },
                        new
                        {
                            Id = 145,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6851),
                            Description = "Identify and collect wild edible plants, mushrooms, and berries. Connects you with nature's bounty.",
                            Name = "Foraging",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6851)
                        },
                        new
                        {
                            Id = 146,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6852),
                            Description = "Navigate through terrain using a map and compass. Combines hiking with navigational challenges.",
                            Name = "Orienteering",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6853)
                        },
                        new
                        {
                            Id = 147,
                            CreatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6853),
                            Description = "Search for buried metals and artifacts. Treasure hunting hobby that gets you outdoors.",
                            Name = "Metal Detecting",
                            UpdatedAt = new DateTime(2026, 6, 29, 18, 21, 35, 406, DateTimeKind.Utc).AddTicks(6854)
                        });
                });

            modelBuilder.Entity("Backend.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("IX_Places_CommunityId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Places_CreatedAt");

                    b.HasIndex("Score")
                        .HasDatabaseName("IX_Places_Score");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Places_UserId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Backend.Models.PlaceVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.HasIndex("UserId", "PlaceId")
                        .IsUnique();

                    b.ToTable("PlaceVotes");
                });

            modelBuilder.Entity("Backend.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Score");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Backend.Models.PostVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("PostVotes");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProfileSetupComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.HasOne("Backend.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.Place", "Place")
                        .WithMany("Comments")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Place");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.CommentVote", b =>
                {
                    b.HasOne("Backend.Models.Comment", "Comment")
                        .WithMany("Votes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Place", b =>
                {
                    b.HasOne("Backend.Models.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.PlaceVote", b =>
                {
                    b.HasOne("Backend.Models.Place", "Place")
                        .WithMany("Votes")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Post", b =>
                {
                    b.HasOne("Backend.Models.Community", "Community")
                        .WithMany("Posts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.PostVote", b =>
                {
                    b.HasOne("Backend.Models.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Backend.Models.Community", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Backend.Models.Place", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Backend.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
