// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426201051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "ParentCommentId")
                        .HasDatabaseName("IX_Comments_PostId_ParentCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Backend.Models.CommentVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId", "CommentId")
                        .IsUnique();

                    b.ToTable("CommentVotes");
                });

            modelBuilder.Entity("Backend.Models.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Communities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(8075),
                            Description = "Play football with friends or join a local team. A great team sport that builds endurance, coordination, and teamwork skills.",
                            Name = "Football",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(8080)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9247),
                            Description = "Shoot hoops at your local court. Can be played solo for practice or in teams for competitive games.",
                            Name = "Basketball",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9248)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9250),
                            Description = "Play beach or indoor volleyball. A fun team sport that doesn't require extensive equipment.",
                            Name = "Volleyball",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9250)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9253),
                            Description = "America's pastime - bat, pitch, and field in this strategic team sport.",
                            Name = "Baseball",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9253)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9255),
                            Description = "A high-intensity contact sport requiring strength, speed, and teamwork.",
                            Name = "Rugby",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9255)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9265),
                            Description = "Fast-paced indoor sport combining elements of basketball and soccer.",
                            Name = "Handball",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9265)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9315),
                            Description = "Throw, dodge, and catch in this exciting and energetic team game.",
                            Name = "Dodgeball",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9315)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9317),
                            Description = "Tackle football with strategic plays and intense physicality.",
                            Name = "American Football",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9317)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9319),
                            Description = "A fun, accessible game similar to baseball but played with a large rubber ball.",
                            Name = "Kickball",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9319)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9323),
                            Description = "Roll strikes and spares at your local bowling alley. Great social community for all ages.",
                            Name = "Bowling",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9323)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9325),
                            Description = "A classic racket sport that can be played in singles or doubles. Great for improving reflexes and cardiovascular fitness.",
                            Name = "Tennis",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9325)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9327),
                            Description = "A fast-paced racket sport that can be played casually or competitively. Great for reflexes and agility.",
                            Name = "Badminton",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9328)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9329),
                            Description = "Fast-paced indoor sport requiring quick reflexes. Can be played competitively or just for fun.",
                            Name = "Table Tennis (Ping Pong)",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9330)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9331),
                            Description = "Intense racket sport played in a four-walled court. Excellent cardio workout.",
                            Name = "Squash",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9332)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9333),
                            Description = "A paddle sport combining elements of tennis, badminton, and table tennis. Easy to learn and very social.",
                            Name = "Pickleball",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9334)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9335),
                            Description = "High-energy racket sport played in an enclosed court with a hollow rubber ball.",
                            Name = "Racquetball",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9335)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9337),
                            Description = "Take a simple walk around your neighborhood or local park. Perfect for clearing your mind and getting light exercise.",
                            Name = "Walking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9337)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9340),
                            Description = "Explore nature trails and mountain paths. From easy trails to challenging climbs, there's a hike for everyone.",
                            Name = "Hiking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9341)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9342),
                            Description = "Whether you're training for a marathon or just want to stay fit, running is an accessible and effective exercise.",
                            Name = "Running/Jogging",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9343)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9344),
                            Description = "Ride a bicycle for leisure or exercise. Great for exploring your city or countryside while getting a good workout.",
                            Name = "Cycling",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9345)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9346),
                            Description = "Observe and identify birds in their natural habitat. A peaceful outdoor community that connects you with nature.",
                            Name = "Bird Watching",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9347)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9348),
                            Description = "Enjoy outdoor meals in parks or scenic locations. Great for relaxation and socializing.",
                            Name = "Picnicking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9348)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9350),
                            Description = "Observe the night sky, constellations, and celestial events. A peaceful and awe-inspiring community.",
                            Name = "Stargazing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9350)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9351),
                            Description = "Throw a frisbee in the park. Can be casual tossing or competitive ultimate frisbee.",
                            Name = "Frisbee",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9352)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9353),
                            Description = "Practice yoga for flexibility, strength, and mental clarity. Suitable for all levels and can be done at home or in a studio.",
                            Name = "Yoga",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9354)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9355),
                            Description = "Build strength and muscle through resistance training. Can be done at the gym or at home with appropriate equipment.",
                            Name = "Weight Training",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9356)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9357),
                            Description = "Low-impact exercise focusing on core strength, flexibility, and body awareness. Great for all fitness levels.",
                            Name = "Pilates",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9358)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9359),
                            Description = "High-intensity functional fitness program combining weightlifting, cardio, and gymnastics.",
                            Name = "CrossFit",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9360)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9361),
                            Description = "Dance-based fitness class with energetic Latin and international music.",
                            Name = "Zumba",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9362)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9363),
                            Description = "High-energy stationary bike workout often done in group classes.",
                            Name = "Spinning/Indoor Cycling",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9364)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9365),
                            Description = "Cardiovascular exercise routine performed to music, often in a group setting.",
                            Name = "Aerobics",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9366)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9367),
                            Description = "Ballet-inspired workout focusing on low-impact, high-intensity movements.",
                            Name = "Barre",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9368)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9369),
                            Description = "Improve flexibility and reduce muscle tension through dedicated stretching routines.",
                            Name = "Stretching",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9369)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9373),
                            Description = "Bodyweight exercises like push-ups, pull-ups, and squats. No equipment needed.",
                            Name = "Calisthenics",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9373)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9375),
                            Description = "Swim for fitness, recreation, or competition. Excellent full-body workout that's easy on the joints.",
                            Name = "Swimming",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9375)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9377),
                            Description = "Ride ocean waves on a surfboard. An exciting water sport that builds strength and balance.",
                            Name = "Surfing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9377)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9379),
                            Description = "Paddle through calm waters or tackle rapids in a kayak. Great for exploring waterways and building upper body strength.",
                            Name = "Kayaking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9379)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9381),
                            Description = "Stand-up paddleboarding on calm waters. Great core workout and peaceful way to explore.",
                            Name = "Paddleboarding (SUP)",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9381)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9382),
                            Description = "Intense team water sport combining swimming, ball handling, and strategy.",
                            Name = "Water Polo",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9383)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9405),
                            Description = "Explore underwater worlds with scuba equipment. Requires certification but offers unique experiences.",
                            Name = "Scuba Diving",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9405)
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9407),
                            Description = "Swim on the water surface while viewing underwater attractions through a snorkel mask.",
                            Name = "Snorkeling",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9407)
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9409),
                            Description = "Paddle a canoe through rivers, lakes, or calm seas. Great for nature exploration.",
                            Name = "Canoeing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9409)
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9411),
                            Description = "High-speed water sport on a personal watercraft. Thrilling and adrenaline-pumping.",
                            Name = "Jet Skiing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9411)
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9413),
                            Description = "Navigate waters using wind power in a sailboat. Combines skill, strategy, and nature.",
                            Name = "Sailing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9414)
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9415),
                            Description = "Express yourself through painting with watercolors, acrylics, or oils. Perfect for relaxation and creativity.",
                            Name = "Painting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9416)
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9417),
                            Description = "Sketch and draw with pencils, charcoal, or digital tools. A portable and accessible creative outlet.",
                            Name = "Drawing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9417)
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9419),
                            Description = "Capture moments and express your artistic vision through photography. Can be done with a phone or professional camera.",
                            Name = "Photography",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9419)
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9421),
                            Description = "Create three-dimensional art with clay, stone, metal, or other materials.",
                            Name = "Sculpting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9421)
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9423),
                            Description = "Create functional or decorative ceramic pieces. A hands-on art form that's both creative and meditative.",
                            Name = "Pottery",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9423)
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9425),
                            Description = "Create art using digital tools like tablets and software. Modern artistic expression.",
                            Name = "Digital Art",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9425)
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9427),
                            Description = "The art of beautiful handwriting. Practice various lettering styles with pens and brushes.",
                            Name = "Calligraphy",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9427)
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9429),
                            Description = "Japanese paper folding art. Create intricate designs from simple paper squares.",
                            Name = "Origami",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9429)
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9431),
                            Description = "Create visual content for digital and print media. Combine art and communication.",
                            Name = "Graphic Design",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9431)
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9433),
                            Description = "Bring drawings and characters to life through frame-by-frame or digital animation.",
                            Name = "Animation",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9433)
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9435),
                            Description = "Design and create jewelry pieces using various materials and techniques.",
                            Name = "Jewelry Making",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9435)
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9437),
                            Description = "Create custom candles with different scents, colors, and designs.",
                            Name = "Candle Making",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9437)
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9439),
                            Description = "Craft handmade soaps with natural ingredients and custom fragrances.",
                            Name = "Soap Making",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9439)
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9440),
                            Description = "Build furniture, decorations, or art pieces from wood. Satisfying hands-on craft.",
                            Name = "Woodworking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9441)
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9442),
                            Description = "Craft items from leather including wallets, bags, and belts.",
                            Name = "Leatherworking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9443)
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9444),
                            Description = "Learn to play acoustic or electric guitar. Great for self-expression and can be enjoyed solo or in a band.",
                            Name = "Guitar",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9445)
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9446),
                            Description = "Learn classical pieces or contemporary songs on the piano. A versatile instrument suitable for all ages.",
                            Name = "Piano",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9447)
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9448),
                            Description = "Practice singing alone or join a choir. Express yourself through music and improve your vocal skills.",
                            Name = "Singing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9449)
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9450),
                            Description = "Learn rhythm and coordination through drumming. Great stress relief and physical workout.",
                            Name = "Drums",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9451)
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9452),
                            Description = "Master this elegant string instrument. Requires dedication but offers beautiful musical expression.",
                            Name = "Violin",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9452)
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9454),
                            Description = "Mix and create music using turntables or digital equipment. Perfect for music enthusiasts.",
                            Name = "DJing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9454)
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9477),
                            Description = "Create original music using digital audio workstations and software.",
                            Name = "Music Production",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9478)
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9479),
                            Description = "Provide the rhythmic foundation in bands or practice solo. Essential in many music genres.",
                            Name = "Bass Guitar",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9480)
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9481),
                            Description = "Learn this expressive wind instrument popular in jazz, classical, and contemporary music.",
                            Name = "Saxophone",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9482)
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9483),
                            Description = "Create percussion sounds and music with your mouth. No equipment needed, just practice.",
                            Name = "Beatboxing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9484)
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9485),
                            Description = "Play the classic strategy game of chess. Improve your tactical thinking and problem-solving skills.",
                            Name = "Chess",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9486)
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9488),
                            Description = "Gather friends and family for board game nights. From strategy games to party games, there's something for everyone.",
                            Name = "Board Games",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9488)
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9508),
                            Description = "Play video games on console, PC, or mobile. From casual puzzle games to competitive esports.",
                            Name = "Video Gaming",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9509)
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9510),
                            Description = "Play poker, bridge, magic the gathering, or casual card games with friends.",
                            Name = "Card Games",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9511)
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9512),
                            Description = "Work on jigsaw puzzles, crosswords, sudoku, or other brain teasers.",
                            Name = "Puzzle Solving",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9513)
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9514),
                            Description = "Master the classic 3D combination puzzle. Great for developing spatial reasoning.",
                            Name = "Rubik's Cube",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9514)
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9516),
                            Description = "Throw darts at a target board. Fun pub game that improves focus and precision.",
                            Name = "Darts",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9516)
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9518),
                            Description = "Play pool, snooker, or other cue sports at a table. Strategic and social community.",
                            Name = "Pool/Billiards",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9518)
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9520),
                            Description = "Test your knowledge in trivia nights or quiz games. Great for groups and learning.",
                            Name = "Trivia/Quiz Games",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9520)
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9522),
                            Description = "Solve puzzles and riddles to 'escape' from a themed room within a time limit.",
                            Name = "Escape Rooms",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9522)
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9524),
                            Description = "Experiment in the kitchen with new recipes. Cook meals for yourself or loved ones.",
                            Name = "Cooking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9524)
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9525),
                            Description = "Bake bread, cakes, cookies, and pastries. A precise and rewarding culinary art.",
                            Name = "Baking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9526)
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9527),
                            Description = "Explore different coffee beans, roasts, and brewing methods. Develop your palate.",
                            Name = "Coffee Tasting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9528)
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9529),
                            Description = "Sample and appreciate different wines. Learn about varieties, regions, and pairing.",
                            Name = "Wine Tasting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9530)
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9531),
                            Description = "Brew your own beer, cider, or kombucha. A fascinating blend of science and art.",
                            Name = "Homebrewing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9532)
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9533),
                            Description = "Learn various dance styles from salsa to hip-hop. Great exercise and a fun social community.",
                            Name = "Dancing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9534)
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9535),
                            Description = "Give back to your community through volunteer work. A rewarding way to make a positive impact.",
                            Name = "Volunteering",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9536)
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9537),
                            Description = "Join a group to read and discuss books. Combine reading with social interaction.",
                            Name = "Book Club",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9537)
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9539),
                            Description = "Dive into books, whether fiction, non-fiction, or poetry. Expand your knowledge and imagination.",
                            Name = "Reading",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9539)
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9541),
                            Description = "Study a new language through apps, courses, or tutors. Expand your communication skills and cultural understanding.",
                            Name = "Learning a Language",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9541)
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9543),
                            Description = "Learn to code in various programming languages. Build apps, websites, or automate tasks.",
                            Name = "Coding/Programming",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9543)
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9545),
                            Description = "Creative writing, journaling, or blogging. Express thoughts and develop storytelling skills.",
                            Name = "Writing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9545)
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9547),
                            Description = "Create and share audio content on communities you're passionate about. Express ideas and connect with audiences.",
                            Name = "Podcasting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9547)
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9548),
                            Description = "Share your thoughts, experiences, or expertise through written or video blogs.",
                            Name = "Blogging/Vlogging",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9549)
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9550),
                            Description = "Take structured online courses on platforms like Coursera, Udemy, or edX. Learn anything from anywhere.",
                            Name = "Online Courses",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9551)
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9552),
                            Description = "Study celestial objects and phenomena. Combine observation with scientific learning.",
                            Name = "Astronomy",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9553)
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9554),
                            Description = "Explore philosophical texts and ideas. Develop critical thinking and question fundamental concepts.",
                            Name = "Philosophy",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9555)
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9556),
                            Description = "Deep dive into historical periods, events, or figures. Understand the past to inform the present.",
                            Name = "History Research",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9557)
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9558),
                            Description = "Practice mindfulness and meditation to reduce stress and improve mental clarity. Can be done anywhere.",
                            Name = "Meditation",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9559)
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9560),
                            Description = "Grow plants, flowers, or vegetables. A relaxing hobby that connects you with nature.",
                            Name = "Gardening",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9561)
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9562),
                            Description = "Practice this gentle martial art focused on slow, flowing movements and breath control.",
                            Name = "Tai Chi",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9563)
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9564),
                            Description = "Learn massage techniques or receive professional massages for relaxation and muscle relief.",
                            Name = "Massage Therapy",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9565)
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9566),
                            Description = "Use essential oils for therapeutic benefits. Promote relaxation and well-being.",
                            Name = "Aromatherapy",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9566)
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9568),
                            Description = "Write daily thoughts, gratitude, or reflections. Great for mental health and self-awareness.",
                            Name = "Journaling",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9568)
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9588),
                            Description = "Immerse yourself in nature to reduce stress and improve well-being. Simply be present in natural settings.",
                            Name = "Nature Bathing (Shinrin-Yoku)",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9588)
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9590),
                            Description = "Practice controlled breathing techniques to reduce stress and improve focus.",
                            Name = "Breathing Exercises",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9590)
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9592),
                            Description = "Relax in hot water or steam rooms. Great for muscle recovery and stress relief.",
                            Name = "Hot Tub/Sauna",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9592)
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9594),
                            Description = "Enjoy music for relaxation, motivation, or pure pleasure. Create playlists or explore new genres.",
                            Name = "Listening to Music",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9594)
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9596),
                            Description = "Traditional Japanese martial art focusing on striking techniques and kata forms.",
                            Name = "Karate",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9596)
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9598),
                            Description = "Train in the sweet science. Great cardio workout and learn self-defense.",
                            Name = "Boxing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9598)
                        },
                        new
                        {
                            Id = 110,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9600),
                            Description = "Japanese martial art focused on throws and grappling techniques.",
                            Name = "Judo",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9600)
                        },
                        new
                        {
                            Id = 111,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9602),
                            Description = "Korean martial art known for dynamic kicking techniques and discipline.",
                            Name = "Taekwondo",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9602)
                        },
                        new
                        {
                            Id = 112,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9604),
                            Description = "Ground-fighting martial art focused on submissions and positional control.",
                            Name = "Brazilian Jiu-Jitsu",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9604)
                        },
                        new
                        {
                            Id = 113,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9606),
                            Description = "Downhill or cross-country skiing in winter. An exhilarating sport for snow enthusiasts.",
                            Name = "Skiing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9606)
                        },
                        new
                        {
                            Id = 114,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9608),
                            Description = "Ride down snowy slopes on a snowboard. Dynamic and exciting winter sport.",
                            Name = "Snowboarding",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9608)
                        },
                        new
                        {
                            Id = 115,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9610),
                            Description = "Glide on ice at a rink. Fun winter community that builds balance and leg strength.",
                            Name = "Ice Skating",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9610)
                        },
                        new
                        {
                            Id = 116,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9612),
                            Description = "Fast-paced team sport played on ice. Requires skating ability and competitive spirit.",
                            Name = "Ice Hockey",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9612)
                        },
                        new
                        {
                            Id = 117,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9614),
                            Description = "Slide down snowy hills on sleds. Simple, fun winter community for all ages.",
                            Name = "Sledding/Tobogganing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9614)
                        },
                        new
                        {
                            Id = 118,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9616),
                            Description = "Perform in plays or take acting classes. Express emotions and stories through performance.",
                            Name = "Acting/Theater",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9616)
                        },
                        new
                        {
                            Id = 119,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9618),
                            Description = "Write and perform comedy routines. Make people laugh while expressing your unique voice.",
                            Name = "Stand-up Comedy",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9618)
                        },
                        new
                        {
                            Id = 120,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9620),
                            Description = "Perform unscripted comedy based on audience suggestions. Develops quick thinking and creativity.",
                            Name = "Improv Comedy",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9620)
                        },
                        new
                        {
                            Id = 121,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9622),
                            Description = "Learn and perform magic illusions. Entertain others with sleight of hand and misdirection.",
                            Name = "Magic Tricks",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9622)
                        },
                        new
                        {
                            Id = 122,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9624),
                            Description = "Learn to juggle balls, clubs, or other objects. Impressive skill that improves coordination.",
                            Name = "Juggling",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9624)
                        },
                        new
                        {
                            Id = 123,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9626),
                            Description = "The art of silent acting through exaggerated gestures and expressions.",
                            Name = "Mime",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9626)
                        },
                        new
                        {
                            Id = 124,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9628),
                            Description = "Create garments and accessories with knitting needles and yarn. Relaxing and productive.",
                            Name = "Knitting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9628)
                        },
                        new
                        {
                            Id = 125,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9630),
                            Description = "Create items using a crochet hook and yarn. Similar to knitting but with different techniques.",
                            Name = "Crocheting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9630)
                        },
                        new
                        {
                            Id = 126,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9632),
                            Description = "Make or repair clothing and fabric items. Practical skill that allows for creative expression.",
                            Name = "Sewing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9632)
                        },
                        new
                        {
                            Id = 127,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9634),
                            Description = "Decorate fabric with needle and thread designs. Detailed handwork that creates beautiful patterns.",
                            Name = "Embroidery",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9634)
                        },
                        new
                        {
                            Id = 128,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9636),
                            Description = "Sew layers of fabric together to create quilts. Combines artistry with practical warmth.",
                            Name = "Quilting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9636)
                        },
                        new
                        {
                            Id = 129,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9638),
                            Description = "Create fabric by interlacing threads on a loom. Ancient craft with modern applications.",
                            Name = "Weaving",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9638)
                        },
                        new
                        {
                            Id = 130,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9655),
                            Description = "Indoor or outdoor climbing that builds strength, problem-solving skills, and confidence.",
                            Name = "Rock Climbing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9655)
                        },
                        new
                        {
                            Id = 131,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9657),
                            Description = "Climb shorter walls without ropes, using crash pads. Great intro to climbing.",
                            Name = "Bouldering",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9657)
                        },
                        new
                        {
                            Id = 132,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9659),
                            Description = "Ride and perform tricks on a skateboard. A creative sport that builds balance and coordination.",
                            Name = "Skateboarding",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9659)
                        },
                        new
                        {
                            Id = 133,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9661),
                            Description = "Navigate urban environments efficiently using running, jumping, and climbing. Develops athleticism and creativity.",
                            Name = "Parkour",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9661)
                        },
                        new
                        {
                            Id = 134,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9663),
                            Description = "Perform tricks and stunts on BMX bicycles. Combines cycling with extreme sports.",
                            Name = "BMX Biking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9663)
                        },
                        new
                        {
                            Id = 135,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9665),
                            Description = "Ride bicycles off-road on rugged terrain. Adventurous and challenging.",
                            Name = "Mountain Biking",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9665)
                        },
                        new
                        {
                            Id = 136,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9666),
                            Description = "Jump from heights while connected to an elastic cord. Ultimate adrenaline rush.",
                            Name = "Bungee Jumping",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9667)
                        },
                        new
                        {
                            Id = 137,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9668),
                            Description = "Jump from aircraft and freefall before deploying a parachute. Unforgettable experience.",
                            Name = "Skydiving",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9669)
                        },
                        new
                        {
                            Id = 138,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9670),
                            Description = "Spend nights outdoors in a tent or RV. Experience nature and disconnect from daily routines.",
                            Name = "Camping",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9671)
                        },
                        new
                        {
                            Id = 139,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9672),
                            Description = "Cast a line in rivers, lakes, or the ocean. A relaxing pastime that can be social or solitary.",
                            Name = "Fishing",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9673)
                        },
                        new
                        {
                            Id = 140,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9674),
                            Description = "Use GPS to find hidden containers (geocaches) placed by others. Modern treasure hunting.",
                            Name = "Geocaching",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9675)
                        },
                        new
                        {
                            Id = 141,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9676),
                            Description = "Ride horses on trails or in arenas. Connect with animals while enjoying outdoor exercise.",
                            Name = "Horseback Riding",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9677)
                        },
                        new
                        {
                            Id = 142,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9678),
                            Description = "Shoot arrows at targets with a bow. Ancient skill requiring focus and precision.",
                            Name = "Archery",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9679)
                        },
                        new
                        {
                            Id = 143,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9680),
                            Description = "Play golf at a course or practice at a driving range. A social sport that combines skill and strategy.",
                            Name = "Golf",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9681)
                        },
                        new
                        {
                            Id = 144,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9682),
                            Description = "Like golf but with frisbees. Throw discs into baskets across a course. Low cost and accessible.",
                            Name = "Disc Golf",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9683)
                        },
                        new
                        {
                            Id = 145,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9684),
                            Description = "Identify and collect wild edible plants, mushrooms, and berries. Connects you with nature's bounty.",
                            Name = "Foraging",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9685)
                        },
                        new
                        {
                            Id = 146,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9686),
                            Description = "Navigate through terrain using a map and compass. Combines hiking with navigational challenges.",
                            Name = "Orienteering",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9687)
                        },
                        new
                        {
                            Id = 147,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9688),
                            Description = "Search for buried metals and artifacts. Treasure hunting hobby that gets you outdoors.",
                            Name = "Metal Detecting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9689)
                        },
                        new
                        {
                            Id = 148,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9690),
                            Description = "Build scale models of vehicles, buildings, or figures. Detail-oriented hobby requiring patience.",
                            Name = "Model Building",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9691)
                        },
                        new
                        {
                            Id = 149,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9692),
                            Description = "Collect stamps, coins, cards, or other items. Combines research with the thrill of the hunt.",
                            Name = "Collecting",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9693)
                        },
                        new
                        {
                            Id = 150,
                            CreatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9694),
                            Description = "Fly drones and capture aerial footage. Modern hobby combining technology with creativity.",
                            Name = "Drone Flying",
                            UpdatedAt = new DateTime(2026, 4, 26, 20, 10, 50, 746, DateTimeKind.Utc).AddTicks(9695)
                        });
                });

            modelBuilder.Entity("Backend.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId")
                        .HasDatabaseName("IX_Events_CommunityId");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("IX_Events_OrganizerId");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("IX_Events_ScheduledAt");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Backend.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommunityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Score");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Backend.Models.PostVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique();

                    b.ToTable("PostVotes");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProfileSetupComplete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.HasOne("Backend.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Backend.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.CommentVote", b =>
                {
                    b.HasOne("Backend.Models.Comment", "Comment")
                        .WithMany("Votes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Event", b =>
                {
                    b.HasOne("Backend.Models.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Backend.Models.User", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Backend.Models.Post", b =>
                {
                    b.HasOne("Backend.Models.Community", "Community")
                        .WithMany("Posts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.PostVote", b =>
                {
                    b.HasOne("Backend.Models.Post", "Post")
                        .WithMany("Votes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Comment", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Backend.Models.Community", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Backend.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
